### ISSUE TITLE
Add utilities like flexboxgrid

### ISSUE THREAD

**Issue by azz** [azz/styled-css-grid#5]
Many of the the utilities implemented in [flexboxgrid](http://flexboxgrid.com/) can be implemented in `display: grid`, this library should offer shorthands for them too:

- [x] Offsets (done in #10 via `left` and `top`)
- [x] Alignment (done in #10 via `center` and `middle`)
- [x] Distribution (done in #22 via `justifyContent` and `alignContent`)
- [x] Reordering (done in #10 via `flow`, `left` and `top`)
- [x] ~Reversing~ Not really applicable

**Comment by azz** [comment]
Closing as all tasks are complete!
